# Creating classification problem for Iris dataset

# 1)- Import key Modules

In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

import pickle
import requests , json

# 2)- Loading data

In [2]:
iris = datasets.load_iris()

In [3]:
# Split dataset into X and y

X = iris.data
y = iris.target

In [4]:
# train-test split
X_train, X_test , y_train , y_test = train_test_split(X,y)

In [5]:
X_test

array([[6.7, 3.1, 4.7, 1.5],
       [5.6, 3. , 4.5, 1.5],
       [6. , 2.2, 4. , 1. ],
       [5.1, 3.8, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [5.1, 3.7, 1.5, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 3.2, 5.3, 2.3],
       [4.6, 3.6, 1. , 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.6, 2.9, 4.6, 1.3],
       [6.7, 3.3, 5.7, 2.1],
       [5.7, 2.6, 3.5, 1. ],
       [4.4, 3.2, 1.3, 0.2],
       [6.7, 3.3, 5.7, 2.5],
       [5.5, 2.5, 4. , 1.3],
       [4.8, 3.4, 1.6, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [6.1, 3. , 4.6, 1.4],
       [7. , 3.2, 4.7, 1.4],
       [5.4, 3.9, 1.7, 0.4],
       [4.9, 2.5, 4.5, 1.7],
       [6.8, 3. , 5.5, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [5.4, 3.7, 1.5, 0.2],
       [6.8, 2.8, 4.8, 1.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.5, 2.4, 3.8, 1.1],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5. , 3

# 3)- Model

In [6]:
rfc= RandomForestClassifier()

In [7]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

# 4)- Evaluate Model

In [8]:
y_pred=rfc.predict(X_test)

In [9]:
print("Accuracy = %0.2f" % accuracy_score(y_test, y_pred))

Accuracy = 0.97


In [10]:
print(classification_report (y_test , y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.93      1.00      0.97        14
           2       1.00      0.90      0.95        10

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



# 5)- Model Serialization

In [11]:
pickle.dump(rfc , open("iris_model.pkl","wb"))

In [12]:
model_rfc=pickle.load(open("iris_model.pkl","rb"))

In [13]:
model_rfc

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

**to confirm if it has same results**

In [14]:
print(classification_report(y_test, model_rfc.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.93      1.00      0.97        14
           2       1.00      0.90      0.95        10

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



#### Out of sample

In [15]:
value=[[3, 5, 4, 2]]
type(value)

list

In [16]:
value=np.asarray(value)

In [17]:
value.shape

(1, 4)

In [18]:
value

array([[3, 5, 4, 2]])

In [19]:
model_rfc.predict(value)

array([1])

In [20]:
model_rfc.predict([[3, 5, 4, 2]])

array([1])

#### json image

In [21]:
iris_json= [{"sl": 3,"sw":5,"pl":4,"pw":2,}]
iris_json

[{'sl': 3, 'sw': 5, 'pl': 4, 'pw': 2}]

In [22]:
type(iris_json)

list

In [23]:
iris_json=np.asarray(iris_json)
type(iris_json)

numpy.ndarray

In [24]:
iris_json.shape

(1,)

In [ ]:
iris_json

# 6)- flask service

In [25]:
url='http://127.0.0.1:5000/api/'

In [26]:
data=json.dumps([{'sl':5.84,'sw':3.0,'pl':3.75,'pw':1.1}])

In [27]:
r=requests.post(url , data)

In [28]:
print(r.json())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)